vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        products:
            uri_prefix: /images/products
            upload_destination: 's3.storage'
            #upload_destination: '%kernel.project_dir%/public/images/products'
